name: GLOBAL VILLAGE SCHOOL
favicon: null
layout_spectrum: 0.17022
typography_spectrum: 0.34911
title: "'It Takes A Global Village to Raise a Global Citizen'"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#003399'
    - '#3366cc'
    - '#6699ff'
    - '#dcd9cf'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
