name: GLOBAL VILLAGE SCHOOL
favicon: null
layout_spectrum: 0.7917194550391287
typography_spectrum: 0.68515
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#4a4a4a'
    - '#939393'
    - '#017ce4'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
